### ISSUE TITLE
First of all, thank you for your work. Can you provide a Baidu Cloud download method for the Kitti 360 dataset? I am unable to download on the official website.

### ISSUE THREAD

**Issue by myself0816** [jamycheung/DELIVER#1]
First of all, thank you for your work. Can you provide a Baidu Cloud download method for the Kitti 360 dataset? I am unable to download on the official website.

**Comment by jamycheung** [comment]
Hi, thanks for your interest. Sorry we cannot provide other download method. 
To download the KITTI360 dataset, please check their official [website](https://www.cvlibs.net/datasets/kitti-360/index.php).

**Comment by ascacdsaa** [comment]
请问您找到kitti 360的数据集吗，我也遇到了同样的问题
