### ISSUE TITLE
Semantic masks values

### ISSUE THREAD

**Issue by GiuseppeT00** [jamycheung/DELIVER#11]
Hi there, first congrats for the amazing work behind the deliver dataset. I would ask you a question about the semantic masks. You have 25 classes, so we expect values in the range [0, 24] in semantic masks, but I see values in range [0, 25]. 
- Why in the dataset class (deliver.py file), you do sample['mask'][sample['mask']==255]=0, and then sample['mask']-=1?
- I assume that 255 label is for background, since you ignore it, it's right?
Thank you in advance!

**Comment by 1404561326521** [comment]
> 您好，首先祝贺交付数据集背后的出色工作。我想问你一个关于语义掩码的问题。您有 25 个类，因此我们期望语义掩码中的值在 [0, 24] 范围内，但我看到的值在 [0, 25] 范围内。
> 
> * 为什么在数据集类（deliver.py 文件）中，您执行sample['mask'][sample['mask']==255]=0，然后sample['mask']-=1？
> * 我认为 255 标签是背景，既然你忽略了它，是对的吗？
>   先感谢您！
[0, 25]表示的应该是从0到24，不包括25

**Comment by jamycheung** [comment]
Hi, thanks for your interest. 

The dataloader of the DELIVER dataset is correct. You can check that in [deliver.py](https://github.com/jamycheung/DELIVER/blob/main/semseg/datasets/deliver.py).
