### ISSUE TITLE
About Event modality

### ISSUE THREAD

**Issue by Candy-Crusher** [jamycheung/DELIVER#24]
Is there any details about experiments on DDD17 and DSEC?

**Comment by elnino9ykl** [comment]
Please refer to 

EISNet: A Multi-Modal Fusion Network for Semantic Segmentation With Events and Images
https://ieeexplore.ieee.org/abstract/document/10477577

SAM-Event-Adapter: Adapting Segment Anything Model for Event-RGB Semantic Segmentation
https://ieeexplore.ieee.org/abstract/document/10611127

Thanks

**Comment by Candy-Crusher** [comment]
Is these results trained from scratch on DSEC-Semantic? I've tried to reproduce the reults but failed.

**Comment by elnino9ykl** [comment]
Please refer to the implementation details in the respective papers. Thanks.

**Comment by Candy-Crusher** [comment]
The respective papers did not provide detailed implementation information. Given that the results of the DSEC dataset have been published on your GitHub repository and listed on the PaperWithCode rankings, I believe it would be beneficial if further details could be provided to ensure the reproducibility and reliability of the results.

**Comment by elnino9ykl** [comment]
Good point. The rankings are based on the respective papers. For reproducing RGB-Event results, you could also check the CMNeXt model on DeLiVER and KITTI360 datasets. 

In the first referenced paper, they clearly described the implementation details on page 8645.
