### ISSUE TITLE
Lidar dataset

### ISSUE THREAD

**Issue by saeed5959** [jamycheung/DELIVER#3]
thankyou for your work!
your dataset consists of RGB, Lidar, Depth and Event. and you have used Lidar data in a image format.
I want to know that can you provide me, your Lidar data in a 3d pointcloud data format ? not image.

Lidar pointcloud  data : (x,y,z)

I am working in a academic research project that I need to a RGBD data and Lidara data for a same scene.

**Comment by jamycheung** [comment]
Hi Saeed, thanks for your interest. 
We are still working on the 3D point cloud and the event data. Please stay tuned.

**Comment by saeed5959** [comment]
whenever it's ready, let me know!
thanks
