### ISSUE TITLE
Visualization of test results

### ISSUE THREAD

**Issue by Sci-Epiphany** [jamycheung/DELIVER#4]
First, thanks to the authors for their wonderful work. I did not find the visualization code of the prediction result in your code, could you please provide it, thank you very much！！

**Comment by jamycheung** [comment]
Hi, thank you for your interest of our work.
About the visualization, you could save the prediction as presented in [this line](https://github.com/jamycheung/DELIVER/blob/main/tools/infer_mm.py#L155).
