### ISSUE TITLE
Unable to get 59.9 mIoU on MFNet data

### ISSUE THREAD

**Issue by HaoZhang1018** [jamycheung/DELIVER#5]
Thank you for this excellent work. I retrain CMNext on the MFNet dataset, but I am unable to achieve the scores reported in the original paper (I obtained mIoU: 57.63). The only difference is that I am using 4 RTX 3090 GPUs and modified the batch size to 3 due to memory constraints. Could you provide some advice to help me reproduce the reported scores (59.9)?

**Comment by jamycheung** [comment]
Hi, thanks for your interest. 
Sorry we have not verified our methods by using RTX 3090 GPUs and the batch size to 3. Maybe a larger epoch or different training strategy could be helpful. 
We appreciate that you provide this result reproduced from your side. Thanks.

**Comment by ggjy** [comment]
Hi @HaoZhang1018, do you obtained the mIoU on val set or test set? When I retrain the CMNeXt, I can only get 59.9 on val set, and get 52.2 on test set. And the weight from GoogleDriver can only  get 52.26 on val set and 50.13 on test set. Is there anything I did wrong? @jamycheung
