### ISSUE TITLE
How do I get depth map data in KITTI360

### ISSUE THREAD

**Issue by SY-Ch** [jamycheung/DELIVER#6]
Excuse me, I am currently working on a project that involves utilizing the KITTI360 dataset for computer vision research. I am particularly interested in the depth map data included in the dataset. I was wondering if you could kindly share some insights on how the depth maps were obtained for the KITTI360 dataset. Upon observation, it seems that the dataset only provides data from fish-eye and left-right cameras. Could you please clarify if the depth maps were acquired using the left-right camera setup? Any information on the process of obtaining the depth maps would be immensely helpful for my research and analysis. Thank you in advance for your time and assistance!

**Comment by jamycheung** [comment]
Hi, thanks for your interest. The depth map data of KITTI-360 dataset is generated by the depth estimation method. You can use the stereo images to estimate the depth map. In our case, we use [AANet](https://github.com/haofeixu/aanet) to generate the depth.
