### ISSUE TITLE
About range-view format

### ISSUE THREAD

**Issue by wyrx** [jamycheung/DELIVER#9]
Thank you for this excellent work. How can I convert LiDAR data to a range-view imagelike format. Could you share the code for this?

**Comment by jamycheung** [comment]
Hi, thanks for your interest. 
We have prepared the front-view LiDAR imagelike format in our dataset, which could be downloaded [here](https://github.com/jamycheung/DELIVER#data-folder-structure).
The transformation from the raw LiDAR to range-view image is not involved yet.
